language: perl
perl:
  - 5.20
  - 5.18
  - 5.16
  - 5.14
  - 5.12
  - 5.10
install:
  - cpanm Dist::Zilla::Plugin::BlockRelease
  - cpanm --installdeps --notest Dist::Zilla::Plugin::PromptIfStale
script:
  - perl Makefile.PL && make
  - echo "no tty on stdin" | make test
